### ISSUE TITLE
Headers load page when clicked

### ISSUE THREAD

**Issue by mikeolteanu** [kkinder/GAEStarterKit#1]
Click on a header such as the logged in user one in the top right. It reloads the current page.

You need to mouseover and choose a sub heading in order to change pages.

It should instead either (a) go to the page of the heading clicked, instead of the current page or (b) do nothing, and allow the mouseover effect to take over.

**Comment by kkinder** [comment]
Hmmm. Indeed. The link anchor used to have a "#" but I removed that so it wouldn't interfere with anchors elsewhere. I'm sure there's a simple solution, though.

**Comment by kkinder** [comment]
@mikeolteanu Should be fixed on latest version. 😄
