### ISSUE TITLE
Consider also adding flask-talisman

### ISSUE THREAD

**Issue by theacodes** [kkinder/GAEStarterKit#2]
Hi, this is a great and comprehensive starter kit. I love the inclusion of security-conscious things such as SeaSurf. To go even further, I'd recommend including [talisman](https://github.com/GoogleCloudPlatform/flask-talisman) to automatically handle a few more security concerns.

(disclaimer, I'm the author of talisman)

**Comment by kkinder** [comment]
Nifty. I wasn't aware of that extension.

**Comment by kkinder** [comment]
Trying it out on a branch for a bit.

**Comment by kkinder** [comment]
Done. It was super-easy.

**Comment by theacodes** [comment]
Cool, thanks!
